app/profile/forms.py
from flask import session, flash
from flask_wtf import Form
from wtforms import StringField, SubmitField, BooleanField, RadioField, ValidationError, PasswordField, HiddenField
from wtforms.validators import DataRequired, Length, IPAddress, Email, StopValidation, EqualTo
from wtforms_components import TimeField
from ..models import User, Node, Association


class NodeInfoForm(Form):
    name = StringField('Access point name')
    ip_address = StringField('IP address')
    dat_start = StringField('Access start time')
    dat_end = StringField('Access end time')
    submit = SubmitField('Submit')

    def validate_name(self, field):
        node_name = session['node_name']
        if Node.query.filter_by(name=field.data).first():
            if Node.query.filter_by(name=node_name).first():
                return
            raise ValidationError('Node with this reference label already exists')

class UserInfoForm(Form):
    first_name = StringField('First name')
    last_name = StringField('Last name')
    email = StringField('Email')
    submit = SubmitField('Submit')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            if field.data == session['email']:
                return
            raise ValidationError('Email already registered')

class UserPassword(Form):
    current_password = PasswordField('Current password', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired(),
                                                     EqualTo('password2', message='Passwords must match')])
    password2 = PasswordField('Confirm Password', validators=[DataRequired()])
    submit = SubmitField('Submit')

class AddUsers(Form):
    email = StringField('User Email', validators=[DataRequired(), Email()])
    iterate = BooleanField('Add More Users To Node', default=False)
    submit = SubmitField('Add User')

class NodeForm(Form):
    submit = SubmitField('Add Users to Access Point')

app/profile/__init__.py
# Blueprint Constructor for profile module
from flask import Blueprint

profile = Blueprint('profile', __name__)

from . import views

app/profile/views.py
# Defines routes used for authentication module
from flask import render_template, redirect, request, url_for, flash, current_app, session
from flask_login import login_user, logout_user, login_required, current_user
from . import profile
from .. import db
from ..models import User, Node, Association, Permissions
from .forms import NodeInfoForm, UserInfoForm, UserPassword, AddUsers, NodeForm
from config import Privileges

@profile.route('/node/<int:id>', methods=['GET', 'POST'])
@login_required
def node(id):
   # form_add = NodeForm()
    node_info = Node.query.filter_by(id=id).first()
    user_id_list = [i.user_id for i in Association.query.filter_by(node_id=node_info.id).all()]
    users = User.query.filter(User.id.in_(user_id_list)).all()
    #if form_add.validate_on_submit():
     #   user = User.query.filter_by(email=session['email']).first()
      #  association = Association.query.filter_by(user_id=user.id, node_id=id).first()
       # if association.can(Privileges.PROFILE_ADD_USERS):
        #    print('Attempting redirect')
         #   redirect(url_for('.add_users', id=id))
        #else:
         #   flash('You are not authorised to add users to this access point')
    #else:
     #   flash('Invalid request')
    return render_template('profile/node.html',
                           node=node_info, users=users,)

"""
@profile.route('/node_edit/<int:id>', methods=['GET', 'POST'])
@login_required
def node_edit(id):   #User role must be SUPER to add or remove others, ADMIN to edit settings
    node = db.session.query(Node).filter_by(id=id).first()
    session['node_name'] = node.name
    form = NodeInfoForm()
    if form.validate_on_submit():
        session.pop('node_name', None)
        node.name = form.name.data
        node.ip_address = form.ip_address.data
        node.dat_start = form.dat_start.data
        node.dat_end = form.dat_end.data
        db.session.commit()
        flash('Access point has been updated')
        return redirect(url_for('.node', id=node.id))
    form.name.data = node.name
    form.ip_address.data = node.ip_address
    form.dat_start = node.dat_start
    form.dat_end = node.dat_end
    session['node_name'] = node.name
    return render_template('profile/node_edit.html',
                           node=node, form=form)
"""

@profile.route('/add_users/<int:id>', methods=['GET', 'POST'])
@login_required
def add_users(id):
    user = User.query.filter_by(email=session['email']).first()
    association = Association.query.filter_by(user_id=user.id, node_id=id).first()
    if association.can(Privileges.PROFILE_ADD_USERS) is not True:
        flash('You are not authorised to grant others access')
        return redirect(url_for('.node', id=id))
    form = AddUsers()
    if form.validate_on_submit():
        node = Node.query.filter_by(id=id).first()
        user = User.query.filter_by(email=form.email.data).first()
        permissions = Permissions.permission_dict['STANDARD']
        association = Association(user_id=user.id, node_id=node.id, permissions=permissions)
        if form.iterate.data is not True:
            db.session.add(association)
            db.session.commit()
            return redirect(url_for('.node', id=node.id))
        db.session.add(association)
        db.session.commit()
        return redirect(url_for('.add_users', id=node.id))
    return render_template('profile/add_users.html', form=form)

@profile.route('/remove_users/<int:id>', methods=['GET', 'POST'])
@login_required
def remove_users(id):
    user = User.query.filter_by(email=session['email']).first()
    association = Association.query.filter_by(user_id=user.id, node_id=id).first()
    print(association.permissions)
    if association.can(Privileges.PROFILE_REMOVE_USERS) is not True:
        flash('You are not authorised to remove others access')
        return redirect(url_for('.node', id=id))
    form = AddUsers()
    if form.validate_on_submit():
        node = Node.query.filter_by(id=id).first()
        user = User.query.filter_by(email=form.email.data).first()
        association = Association.query.filter_by(user_id=user.id, node_id=node.id).first()
        if form.iterate.data is not True:
            db.session.delete(association)
            db.session.commit()
            return redirect(url_for('.node', id=node.id))
        db.session.delete(association)
        db.session.commit()
        return redirect(url_for('.remove_users', id=node.id))
    return render_template('profile/add_users.html', form=form)

@profile.route('/user/<int:id>', methods=['GET', 'POST'])
@login_required
def user(id):
    user = User.query.filter_by(id=id).first()
    node_id_list = [i.node_id for i in Association.query.filter_by(user_id=user.id).all()]
    nodes = Node.query.filter(Node.id.in_(node_id_list)).all()
    return render_template('profile/user.html', user=user, nodes=nodes)

@profile.route('/user_edit/<int:id>', methods=['GET', 'POST'])
@login_required
def user_edit(id):
    user = User.query.filter_by(id=id).first()
    form = UserInfoForm()
    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data
        db.session.commit()
        flash('Profile updated')
        return redirect(url_for('.user', id=user.id))
    form.first_name.data = user.first_name
    form.last_name.data = user.last_name
    form.email.data = user.email
    return render_template('profile/user_edit.html', user=user, form=form)

@profile.route('/user_password/<int:id>', methods=['GET', 'POST'])
@login_required
def user_password(id):
    user = User.query.filter_by(id=id).first()
    form = UserPassword()
    if form.validate_on_submit():
        if user.verify_password(form.current_password.data):
            user.password = form.password.data
            db.session.commit()
            flash('Password updated')
            return redirect(url_for('.user', id=session['user_id']))
        flash('Current and form passwords do not match')
    return render_template('profile/user_password.html', form=form)

app/templates/profile/add_users.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ network }}: Register Node Users{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register Node Users</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/profile/node.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="card">
            <h2 class="card-header">Access Point Information</h2>
            <div class="card-block">
                <ul class="list-group">
                    <li class="list-group-item">Name: {{node['name']}}</li>
                    <li class="list-group-item">IP_Address: {{node['ip_address']}}</li>
                    <li class="list-group-item">Access Time: {{ node['dat_start'] }} - {{ node['dat_end'] }}</li>
                    {% if node['is_open'] %}
                    <li class="list-group-item">Current State: LOCKED</li>
                    {% else %}
                    <li class="list-group-item">Current State: UNLOCKED</li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </div>
</div>
<div><br></div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="card">
            <h2 class="card-header">Connected Users</h2>
            <div class="card-block">
                <ul class="list-group">
                    {% for user in users %}
                    <li class="list-group-item">{{ user['first_name'] }} {{user['last_name'] }}</li>
                    {% endfor %}
                </ul><br>
                <a href="{{ url_for('profile.add_users',id=node['id']) }}" class="btn btn-primary" style="font-size: 2rem;">Add User</a>
                <span>
                    <a href="{{ url_for('profile.remove_users',id=node['id']) }}"class="btn btn-danger" style="font-size: 2rem;">Remove User</a>
                </span>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/node_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="page-header">
</div>
<div class="col-md-6">
    <h3>Access Point Information</h3>
    <br>NAME: {{ node['name'] }}
    <br>IP ADDRESS: {{ node['ip_address'] }}
    <br>ACCESS TIMES: {{ node['dat_start'] }} - {{ node['dat_end'] }}
    {% if node['is_open'] %}
        <br>CURRENT STATE: OPEN
    {% else %}
        <br>CURRENT STATE: LOCKED
    {% endif %}
    <br>
    <div class="col-md-4">
    {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/profile/user.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="card">
            <h2 class="card-header">User Profile Information</h2>
            <div class="card-block">
                <ul class="list-group">
                    <li class="list-group-item">First Name: {{user['first_name']}}</li>
                    <li class="list-group-item">Last Name: {{user['last_name']}}</li>
                    <li class="list-group-item">Email: {{user['email']}}</li>
                </ul><br>
                <a href="#" class="btn btn-primary" style="font-size: 2rem;">Update</a>
                <span><a href="#" class="btn btn-outline-primary" style="font-size: 2rem;">Change Password</a></span>
            </div>
        </div>
    </div>
</div>
<div class="row"><br></div>
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="card">
            <h2 class="card-header">Connected Access Points</h2>
            <div class="card-block">
                <ul class="list-group">
                    <li class="list-group-item active">Administrator Access</li>
                    {% for node in nodes %}
                    <li class="list-group-item">
                        <a href="{{ url_for('profile.node', id=node['id']) }}">{{ node['name']}}</a>
                    </li>
                    {% endfor %}
                </ul><br>
                <ul class="list-group">
                    <li class="list-group-item active">Standard Access</li>
                    {% for node in nodes %}
                    <li class="list-group-item">
                        <a href="{{ url_for('profile.node', id=node['id']) }}">{{ node['name']}}</a>
                    </li>
                    {% endfor %}
                </ul><br>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/profile/user_edit.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="page-header">
</div>
<div class="col-md-6">
    <h3>User Profile Information</h3>
    <br> First Name: {{ user['first_name'] }}
    <br> Last Name: {{ user['last_name'] }}
    <br> Email: {{ user['email'] }}
    <div class="col-md-4">
    {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}

app/templates/profile/user_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="page-header">
    <div class="col-md-4">
        <h3>Change Password Form</h3>
        {{ wtf.quick_form(form) }}
    </div>
</div>
{% endblock %}