app/control/forms.py
from flask import session
from flask_wtf import Form
from wtforms import StringField, SubmitField, BooleanField, ValidationError, RadioField, HiddenField
from wtforms.validators import DataRequired, IPAddress, Email
from ..models import Node, User, Association


# Form to configure Node
class AddNode(Form):
    name = StringField('Reference Label', validators=[DataRequired()])
    ip_address = StringField('IP Address', validators=[DataRequired(), IPAddress()])
    submit = SubmitField('Register Node')

    def validate_name(self, field):
        if Node.query.filter_by(name=field.data).first():
            raise ValidationError('Node with this reference label already exists')

    def validate_ip_address(self, field):
        if Node.query.filter_by(ip_address=field.data).first():
            raise ValidationError('Node with this IP Address already exists')


# Form to add users to Node during it's registration
class AddNodeUsers(Form):
    email = StringField('User Email', validators=[DataRequired(), Email()])
    role = RadioField('User Privilege Level', validators=[DataRequired()],
                      choices=[('STANDARD', 'User'),
                               ('SUPER', 'Super User'),])
    iterate = BooleanField('Add More Users To Node', default=False)
    submit = SubmitField('Add User')

    def validate_email(self, field):
        user = User.query.filter_by(email=field.data).first()        # Returns user object from User table
        if user is None:
            raise ValidationError('This email is not registered on this Network')
        node_name = session['node_name']
        node = Node.query.filter_by(name=node_name).first()               # Return the node object form dictionary
        association = Association.query.filter_by(user_id=user.id, node_id=node.id).scalar()
        if association is not None:
            raise ValidationError('This email is already registered to this Node')

app/control/__init__.py
# Blueprint Constructor for control module
from flask import Blueprint

control = Blueprint('control', __name__)

from . import views

app/control/views.py
# Defines routes used for node control module
from flask import render_template, redirect, request, url_for, session, flash
from flask_login import login_required
from . import control
from .. import db
from ..models import User, Association, Node, Permissions
from .forms import AddNode, AddNodeUsers
from networking import socket_client
from config import Privileges


@control.route('/access', methods=['GET', 'POST'])
@login_required
def access():
    form = request.form
    if request.method == 'POST':
        print(form)
        node_info = db.session.query(Node).filter_by(id=form['id']).first()
        user = User.query.filter_by(email=session['email']).first()
        association = Association.query.filter_by(user_id=user.id, node_id=node_info.id).first()
        if association.can(Privileges.CONTROL_ACCESS):
            (success, new_state) = socket_client(form['is_open'], node_info.ip_address)
            print('Transmission success: ' + str(success) + ' | New node state: '+str(new_state))
            if success:
                if new_state == 'True':
                    node_info.is_open = True
                if new_state =='False':
                    node_info.is_open = False
                db.session.commit()
                flash('Access request successful')
            if success is False:
                flash('Access request could not be completed')
        if association.can(0x03) is not True:
            flash('You are not authorised to make this action')
    return render_template('control/access.html',
                           node_data=node_list())

def node_list():
    user = User.query.filter_by(email=session['email']).first()         # Returns User ID from email of current session user
    node_id_list = [i.node_id for i in Association.query.filter_by(user_id=user.id).all()]  # Returns list of Node IDs that user has access to
    node_data = Node.query.filter(Node.id.in_(node_id_list)).all()      # Returns dictionary containing individual Node data
    return node_data


@control.route('/add_node', methods=['GET', 'POST'])
@login_required
def add_node():
    form = AddNode()
    if form.validate_on_submit():
        node = Node(name=form.name.data,                                    # Builds node object from form config
                    ip_address=form.ip_address.data)
        db.session.add(node)
        db.session.commit()
        session['node_name'] = form.name.data
        return redirect(url_for('.add_node_users'))
    return render_template('control/add_node.html', form=form)


@control.route('/add_node_users', methods=['GET', 'POST'])
@login_required
def add_node_users():
    form = AddNodeUsers()
    print(session['node_name'])
    if form.validate_on_submit():
        node_name = session['node_name']                               # Calls node name from session dictionary
        node = Node.query.filter_by(name=node_name).first()               # Return the node object form dictionary
        user = User.query.filter_by(email=form.email.data).first()        # Returns user object from User table
        try:
            permissions = Permissions.permission_dict[form.role.data]   # Build permissions binary
        except KeyError:
            return redirect(url_for('.add_node_users'))                 # Refresh page for failed role type
        association = Association(user_id=user.id, node_id=node.id, permissions=permissions)        # Builds association object from Association table
        if form.iterate.data is False:                                 # Returns False when add additional users button is not pressed
            db.session.add(association)
            db.session.commit()
            session.pop('node_name', None)                              # Deletes the node linked to this session
            return redirect(url_for('.access'))                 # Redirects to ./control/access page
        db.session.add(association)
        db.session.commit()
        return redirect(url_for('.add_node_users'))
    return render_template('control/add_node_users.html', form=form)                    # Builds add_note.html page

app/templates/control/access.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
{{ super() }}
<div class="row">
    <div class="col-md-3"></div>
    <div class="col-md-6">
        <div class="card">
            <h2 class="card-header">Access Control</h2>
            <div class="card-block">
                    {% for node in node_data %}
                        <div class="card">
                            <div class="card-header"><h2>{{node['name']}}<a
                                    href="{{ url_for('profile.node', id=node['id']) }}" style="padding-left:8em">
                                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span></a></h2>
                            </div>
                            <div class="card-block">
                                <form action="/control/access" method="post"><h2>
                                    <input type="hidden" name="id" value="{{node['id']}}">
                                    <div class="btn-group btn-lg" data-toggle="buttons">
                                        {% if node['is_open'] == True %}
                                        <label class="btn btn-primary active btn-lg">
                                            <input type="radio" name="is_open" id="option1" value="True"
                                                   onchange="this.form.submit();" autocomplete="off" checked><h2>Unlocked</h2>
                                        </label>
                                        <label class="btn btn-primary btn-lg">
                                            <input type="radio" name="is_open" id="option2" value="False"
                                                   onchange="this.form.submit();" autocomplete="off"> <h2>Locked</h2>
                                        </label>
                                        {% else %}
                                        <label class="btn btn-primary btn-lg">
                                            <input type="radio" name="is_open" id="option3" value="True"
                                                   onchange="this.form.submit();" autocomplete="off"> <h2>Unlocked</h2>
                                        </label>
                                        <label class="btn btn-primary active btn-lg">
                                            <input type="radio" name="is_open" id="option4" value="False"
                                                   onchange="this.form.submit();" autocomplete="off" checked> <h2>Locked</h2>
                                        </label>
                                        {% endif %}
                                    </div>
                                </h2></form>
                            </div>
                        </div>
                        <br></div>
                    <br>
                    {% endfor %}
                </div>
                <div class="col-md-4"><br>
                    <button type="button" class="btn btn-secondary">
                        <a href="{{ url_for('control.add_node') }}"><h3>Add Node</h3></a>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{% endblock %}

app/templates/control/access_old.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Access Control</h1>
</div>

{% for node in node_list %}
<form method = "POST">
    <div class="col-md-4">
        <input type="hidden" name="node_name" value="{{ node['name'] }}">
        <br>{{ node['name'] }}<br>
        <a href="{{ node_config }}">Configuration</a><br>
        <div class="btn-group" data-toggle="buttons">
            {% if node['is_open'] %}
                <label class="btn btn-primary active">
                    <input type="radio" name="is_open" id="option1" value = True autocomplete="off" checked> Unlocked
                </label>
                <label class="btn btn-primary">
                    <input type="radio" name="is_open" id="option2" value = False autocomplete="off"> Locked
                </label><br>
            {% else %}
                <label class="btn btn-primary">
                    <input type="radio" name="is_open" id="option3" value = True autocomplete="off" checked> Unlocked
                </label>
                <label class="btn btn-primary active">
                    <input type="radio" name="is_open" id="option4" value = False autocomplete="off"> Locked
                </label>
            {% endif %}
            <div><br><input type="submit" value="Submit"></div>
        </div>
    </div>
</form>
{% endfor %}
<div class="col-md-12">
    <br><br>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

<!-- JAVASCRIPT FUNCTIONS -->
<!--
$('input[name=nodeState]').change(function(){
     $('is_open').submit();});
-->

app/templates/control/add_node.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ network }}: Register Node{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register Node</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/control/add_node_users.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}{{ network }}: Register Node Users{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Register Node Users</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/control/locked.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}Development PiHub: Access Control{% endblock %}

{% block page_content %}
<div class="page-header">
    Hello
</div>

{% endblock %}